//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.225
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWCF.ProxyPerCall {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyPerCall.IServicioPerCall")]
    public interface IServicioPerCall {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPerCall/IncrementaContador", ReplyAction="http://tempuri.org/IServicioPerCall/IncrementaContadorResponse")]
        string IncrementaContador();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPerCallChannel : ClienteWCF.ProxyPerCall.IServicioPerCall, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPerCallClient : System.ServiceModel.ClientBase<ClienteWCF.ProxyPerCall.IServicioPerCall>, ClienteWCF.ProxyPerCall.IServicioPerCall {
        
        public ServicioPerCallClient() {
        }
        
        public ServicioPerCallClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPerCallClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPerCallClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPerCallClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string IncrementaContador() {
            return base.Channel.IncrementaContador();
        }
    }
}
