//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWCF.ProxyWCF {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="enumTipoFecha", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum enumTipoFecha : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Larga = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Corta = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completa = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyWCF.IMiServicioWCF")]
    public interface IMiServicioWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicioWCF/GetData", ReplyAction="http://tempuri.org/IMiServicioWCF/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicioWCF/Fecha", ReplyAction="http://tempuri.org/IMiServicioWCF/FechaResponse")]
        string Fecha();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicioWCF/FechaConTipo", ReplyAction="http://tempuri.org/IMiServicioWCF/FechaConTipoResponse")]
        string FechaConTipo(ClienteWCF.ProxyWCF.enumTipoFecha tipoFecha);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMiServicioWCFChannel : ClienteWCF.ProxyWCF.IMiServicioWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiServicioWCFClient : System.ServiceModel.ClientBase<ClienteWCF.ProxyWCF.IMiServicioWCF>, ClienteWCF.ProxyWCF.IMiServicioWCF {
        
        public MiServicioWCFClient() {
        }
        
        public MiServicioWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiServicioWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public string Fecha() {
            return base.Channel.Fecha();
        }
        
        public string FechaConTipo(ClienteWCF.ProxyWCF.enumTipoFecha tipoFecha) {
            return base.Channel.FechaConTipo(tipoFecha);
        }
    }
}
