//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.225
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWCF.ProxyPerSession {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyPerSession.IServicioPerSession")]
    public interface IServicioPerSession {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPerSession/IncrementaContador", ReplyAction="http://tempuri.org/IServicioPerSession/IncrementaContadorResponse")]
        string IncrementaContador();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPerSessionChannel : ClienteWCF.ProxyPerSession.IServicioPerSession, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPerSessionClient : System.ServiceModel.ClientBase<ClienteWCF.ProxyPerSession.IServicioPerSession>, ClienteWCF.ProxyPerSession.IServicioPerSession {
        
        public ServicioPerSessionClient() {
        }
        
        public ServicioPerSessionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPerSessionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPerSessionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPerSessionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string IncrementaContador() {
            return base.Channel.IncrementaContador();
        }
    }
}
